import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import { LoginProvider } from "@/components/general/LoginContext";
import Login from "@/components/general/Login";

const robotoSlab = Roboto_Slab({
  variable: "--font-robotoSlab",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} antialiased`}>
        <LoginProvider>
          {children} <Login />
        </LoginProvider>
      </body>
    </html>
  );
}
